# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY WHALE
# Only modify it using the whale command line
# See whale --help for further information

FROM node:16-alpine AS development

RUN apk --no-cache update && apk upgrade && \
    apk add --no-cache curl && \
    apk add --no-cache alpine-sdk && \
    apk add --no-cache linux-headers && \
    apk add --no-cache ca-certificates && update-ca-certificates 2>/dev/null && \
    apk add --no-cache bash && \
    apk add --no-cache dumb-init && \
    apk add --no-cache tzdata && \
    curl https://ssmsh-arh.s3.eu-central-1.amazonaws.com/v0.2.1/ssmsh-alpine-amd64 -o /ssmsh && chmod +x /ssmsh && mv /ssmsh /usr/local/bin/ssmsh && \
    apk add --no-cache git && \
    apk add --no-cache libc6-compat

ENV LANG="C.UTF-8"
WORKDIR /app
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["yarn", "dev"]

FROM development
COPY package.json yarn.lock .npmrc ./
RUN yarn install --frozen-lockfile --network-concurrency 1 && yarn cache clean

COPY . ./
